SERVER_NAME = 'localhost:5000'

POSTGRES_USER='admin'
POSTGRES_PASSWORD='yBznASFxqray6j6qkdY9AagpjuaHBJbC'
POSTGRES_DB='wedding_database'
DB_SERVER = 'postgres:5432'
SQLALCHEMY_DB_PREFIX = "postgresql+psycopg2"

SECRET_KEY = ""
SECURITY_PASSWORD_SALT = ""

SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_CHANGEABLE = True